SafeStates/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^fratelliadmin/', include(admin.site.urls)),

    url('^$', TemplateView.as_view(template_name="new-index.html"), name="home"),
    url(r'^search/', include('livability.urls')),
    url(r'^dbadmin/', include('db_admin.urls')),
]

db_admin/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from views import *

urlpatterns = [
    url(r'denied/$', TemplateView.as_view(template_name="denied.html")),

    # Admin
    url(r'add/$', addEntry, name="admin_add"),
    url(r'delete/([0-9]+)/$', deleteEntry, name="admin_delete"),
    url(r'edit/([0-9]+)/$', editEntry, name="admin_edit"),
    url(r'list/$', listEntries, name="admin_list"),
    url(r'show/([0-9]+)/$', showEntry, name="admin_show"),

    url(r'$', listEntries),
]

db_admin/models.py
from django.db import models

# Create your models here.

livability/models.py
from django.db import models

class Tools(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200,null=True,blank=True)
    url = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    year_developed = models.IntegerField(null=True,blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Community_Size(models.Model):
    SIZE_CHOICES = (
        (1, '1-Urban'),
        (2, '2-Rural'),
    )
    toolname = models.ForeignKey(Tools)
    selection = models.SmallIntegerField(choices=SIZE_CHOICES)
    # 1 = Urban, 2 = Rural

    class Meta:
        ordering = ['toolname__name']

    def selection_verbose(self):
        return dict(Community_Size.SIZE_CHOICES)[self.selection]

class Assessment_Focus(models.Model):
    FOCUS_CHOICES = (
        (1, '1-Development or Transportation Projects'),
        (2, '2-Physical Environment of a Community, Neighborhood, or School'),
        (3, '3-Policy, Plan, Codes, or Standards'),
        (4, '4-Walkability, Bikability, and/or Transit Access'),
    )
    toolname = models.ForeignKey(Tools)
    selection = models.SmallIntegerField(choices=FOCUS_CHOICES)
    # 1 = Development or Transportation Project, 2 = Physical Environment of a Community, Neighborhood, or School
    # 3 = Policy, Plan, Codes, or Standards 4 = Walkability, Bikability, and/or Transit access

    class Meta:
        ordering = ['toolname__name']

    def selection_verbose(self):
        return dict(Assessment_Focus.FOCUS_CHOICES)[self.selection]

class Audience(models.Model):
    AUDIENCE_CHOICES = (
        (1, '1-Elected Officials'),
        (2, '2-Laypersons'),
        (3, '3-Planners'),
        (4, '4-PH Professionals'),
        (5, '5-School Officials'),
    )
    toolname = models.ForeignKey(Tools)
    selection = models.SmallIntegerField(choices=AUDIENCE_CHOICES)
    # 1 = Elected Officials, 2 = Laypersons, 3 = Planners, 4 = PH Professionals, 5 = School officials

    class Meta:
        ordering = ['toolname__name']

    def selection_verbose(self):
        return dict(Audience.AUDIENCE_CHOICES)[self.selection]

class Topics(models.Model):
    TOPIC_CHOICES = (
        (0, 'No'),
        (1, 'Yes'),
    )
    toolname = models.OneToOneField(Tools)
    # Yes/no 1/0
    q_transportation = models.SmallIntegerField(choices=TOPIC_CHOICES) #Transportation Choices & Safe, Multimodal Neighborhood
    q_housing = models.SmallIntegerField(choices=TOPIC_CHOICES) # Equitable Housing Options
    q_investment = models.SmallIntegerField(choices=TOPIC_CHOICES) # Investment in Existing Communities
    q_compact = models.SmallIntegerField(choices=TOPIC_CHOICES) # Compact, Mixed-use Design
    q_health = models.SmallIntegerField(choices=TOPIC_CHOICES) # Health-Promoting Design and Policies
    q_preservation = models.SmallIntegerField(choices=TOPIC_CHOICES) # Preservation Rural Areas & Open Space

    class Meta:
        ordering = ['toolname__name']

    def transportation_verbose(self):
        return dict(Topics.TOPIC_CHOICES)[self.q_transportation]
    def housing_verbose(self):
        return dict(Topics.TOPIC_CHOICES)[self.q_housing]
    def investment_verbose(self):
        return dict(Topics.TOPIC_CHOICES)[self.q_investment]
    def compact_verbose(self):
        return dict(Topics.TOPIC_CHOICES)[self.q_compact]
    def health_verbose(self):
        return dict(Topics.TOPIC_CHOICES)[self.q_health]
    def preservation_verbose(self):
        return dict(Topics.TOPIC_CHOICES)[self.q_preservation]

db_admin/forms.py
from django.forms import BooleanField, CharField, Form, Textarea, TextInput


class AddEditForm(Form):
    yearDeveloped = CharField(max_length=4, required=False)
    name = CharField(max_length=200, widget=TextInput(attrs={'size': '100'}))
    author = CharField(max_length=200, required=False, widget=TextInput(attrs={'size': '100'}))
    url = CharField(max_length=200, widget=TextInput(attrs={'size': '100'}))
    description = CharField(widget=Textarea(attrs={'cols': '100'}))
    communitySizeUrban = BooleanField(required=False)
    communitySizeRural = BooleanField(required=False)
    assessmentFocusDevelopment = BooleanField(required=False)
    assessmentFocusPhysical = BooleanField(required=False)
    assessmentFocusPolicy = BooleanField(required=False)
    assessmentFocusWalkability = BooleanField(required=False)
    audienceElected = BooleanField(required=False)
    audienceLaypersons = BooleanField(required=False)
    audiencePlanners = BooleanField(required=False)
    audienceProfessionals = BooleanField(required=False)
    audienceSchool = BooleanField(required=False)
    topicTransportation = BooleanField(required=False)
    topicHousing = BooleanField(required=False)
    topicInvestment = BooleanField(required=False)
    topicCompact = BooleanField(required=False)
    topicHealth = BooleanField(required=False)
    topicPreservation = BooleanField(required=False)

db_admin/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from livability.models import *
from forms import *


@login_required
def addEntry(request):
    dReturn = {}

    if request.method == 'POST':
        form = AddEditForm(request.POST)
        dReturn['form'] = form

        form.is_valid()
        cd = form.cleaned_data

        tool = Tools()
        tool.name = cd['name']
        tool.author = cd['author']
        tool.url = cd['url']

        if cd['yearDeveloped'] != "":
            tool.year_developed = cd['yearDeveloped']
        else:
            tool.year_developed = None

        tool.description = cd['description']
        tool.save()

        if 'communitySizeUrban' in cd:
            communitySize = Community_Size(toolname=tool, selection=1)
            communitySize.save()
        if 'communitySizeRural' in cd:
            communitySize = Community_Size(toolname=tool, selection=2)
            communitySize.save()

        if 'assessmentFocusDevelopment' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=1)
            assessmentFocus.save()
        if 'assessmentFocusPhysical' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=2)
            assessmentFocus.save()
        if 'assessmentFocusPolicy' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=3)
            assessmentFocus.save()
        if 'assessmentFocusWalkability' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=4)
            assessmentFocus.save()

        if 'audienceElected' in cd:
            audience = Audience(toolname=tool, selection=1)
            audience.save()
        if 'audienceLaypersons' in cd:
            audience = Audience(toolname=tool, selection=2)
            audience.save()
        if 'audiencePlanners' in cd:
            audience = Audience(toolname=tool, selection=3)
            audience.save()
        if 'audienceProfessionals' in cd:
            audience = Audience(toolname=tool, selection=4)
            audience.save()
        if 'audienceSchool' in cd:
            audience = Audience(toolname=tool, selection=5)
            audience.save()

        topics = Topics()
        topics.toolname = tool

        if 'topicTransportation' in cd:
            topics.q_transportation = 1
        else:
            topics.q_transportation = 0

        if 'topicHousing' in cd:
            topics.q_housing = 1
        else:
            topics.q_housing = 0

        if 'topicInvestment' in cd:
            topics.q_investment = 1
        else:
            topics.q_investment = 0

        if 'topicCompact' in cd:
            topics.q_compact = 1
        else:
            topics.q_compact = 0

        if 'topicHealth' in cd:
            topics.q_health = 1
        else:
            topics.q_health = 0

        if 'topicPreservation' in cd:
            topics.q_preservation = 1
        else:
            topics.q_preservation = 0

        topics.save()

        return redirect(reverse('admin_show', args=[tool.id]))

    else:
        form = AddEditForm()
        dReturn['form'] = form

        return render(request, "addEditEntry.html", dReturn)


@login_required
def deleteEntry(request, entryId):
    try:
        tool = Tools.objects.get(id = entryId)
    except:
        messages.error(request, "The tool with the id [%s] cannot be found" % entryId)
        return redirect("admin_list")

    try:
        tool.delete()
    except:
        messages.error(request, "There was a problem deleting this tool")
        return redirect("admin_list")
    else:
        messages.success(request, "Tool deleted")

    return redirect("admin_list")


@login_required
def editEntry(request, entryId):
    dReturn = {}
    dReturn['entryId'] = entryId

    try:
        tool = Tools.objects.get(id = entryId)
    except Tools.DoesNotExist:
        messages.error(request, "The tool with the id [%s] cannot be found" % entryId)
        return redirect("admin_list")

    communitySizeUrban = False
    communitySizeRural = False
    assessmentFocusDevelopment = False
    assessmentFocusPhysical = False
    assessmentFocusPolicy = False
    assessmentFocusWalkability = False
    audienceElected = False
    audienceLaypersons = False
    audiencePlanners = False
    audienceProfessionals = False
    audienceSchool = False
    topicTransportation = False
    topicHousing = False
    topicInvestment = False
    topicCompact = False
    topicHealth = False
    topicPreservation = False

    if request.method == 'POST':
        form = AddEditForm(request.POST)
        dReturn['form'] = form

        form.is_valid()
        cd = form.cleaned_data

        tool.name = cd['name']
        tool.author = cd['author']
        tool.url = cd['url']
        if cd['yearDeveloped'] != "":
            tool.year_developed = cd['yearDeveloped']
        else:
            tool.year_developed = None

        tool.description = cd['description']
        tool.save()

        communitySizeList = Community_Size.objects.filter(toolname = tool)
        for item in communitySizeList:
            item.delete()

        if 'communitySizeUrban' in cd:
            communitySize = Community_Size(toolname=tool, selection=1)
            communitySize.save()
        if 'communitySizeRural' in cd:
            communitySize = Community_Size(toolname=tool, selection=2)
            communitySize.save()

        assessmentFocusList = Assessment_Focus.objects.filter(toolname = tool)
        for item in assessmentFocusList:
            item.delete()

        if 'assessmentFocusDevelopment' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=1)
            assessmentFocus.save()
        if 'assessmentFocusPhysical' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=2)
            assessmentFocus.save()
        if 'assessmentFocusPolicy' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=3)
            assessmentFocus.save()
        if 'assessmentFocusWalkability' in cd:
            assessmentFocus = Assessment_Focus(toolname=tool, selection=4)
            assessmentFocus.save()

        audienceList = Audience.objects.filter(toolname = tool)
        for item in audienceList:
            item.delete()

        if 'audienceElected' in cd:
            audience = Audience(toolname=tool, selection=1)
            audience.save()
        if 'audienceLaypersons' in cd:
            audience = Audience(toolname=tool, selection=2)
            audience.save()
        if 'audiencePlanners' in cd:
            audience = Audience(toolname=tool, selection=3)
            audience.save()
        if 'audienceProfessionals' in cd:
            audience = Audience(toolname=tool, selection=4)
            audience.save()
        if 'audienceSchool' in cd:
            audience = Audience(toolname=tool, selection=5)
            audience.save()

        topics = Topics.objects.get(toolname = tool)
        if 'topicTransportation' in cd:
            topics.q_transportation = 1
        else:
            topics.q_transportation = 0

        if 'topicHousing' in cd:
            topics.q_housing = 1
        else:
            topics.q_housing = 0

        if 'topicInvestment' in cd:
            topics.q_investment = 1
        else:
            topics.q_investment = 0

        if 'topicCompact' in cd:
            topics.q_compact = 1
        else:
            topics.q_compact = 0

        if 'topicHealth' in cd:
            topics.q_health = 1
        else:
            topics.q_health = 0

        if 'topicPreservation' in cd:
            topics.q_preservation = 1
        else:
            topics.q_preservation = 0

        topics.save()

        messages.success(request, "Updated this entry")
        return redirect(reverse('admin_show', args=[entryId]))

    else:
        communitySizeList = Community_Size.objects.filter(toolname = tool)
        for item in communitySizeList:
            if item.selection == 1:
                communitySizeUrban = True
            elif item.selection == 2:
                communitySizeRural = True

        assessmentFocusList = Assessment_Focus.objects.filter(toolname = tool)
        for item in assessmentFocusList:
            if item.selection == 1:
                assessmentFocusDevelopment = True
            elif item.selection == 2:
                assessmentFocusPhysical = True
            elif item.selection == 3:
                assessmentFocusPolicy = True
            elif item.selection == 4:
                assessmentFocusWalkability = True

        audienceList = Audience.objects.filter(toolname = tool)
        for item in audienceList:
            if item.selection == 1:
                audienceElected = True
            elif item.selection == 2:
                audienceLaypersons = True
            elif item.selection == 3:
                audiencePlanners = True
            elif item.selection == 4:
                audienceProfessionals = True
            elif item.selection == 5:
                audienceSchool = True

        topics = Topics.objects.get(toolname = tool)
        if topics.q_transportation == 1:
            topicTransportation = True
        if topics.q_health == 1:
            topicHealth = True
        if topics.q_preservation == 1:
            topicPreservation = True
        if topics.q_housing == 1:
            topicHousing = True
        if topics.q_compact == 1:
            topicCompact = True
        if topics.q_investment == 1:
            topicInvestment = True


        form = AddEditForm(initial={
            'yearDeveloped': tool.year_developed,
            'name': tool.name,
            'author': tool.author,
            'url': tool.url,
            'description': tool.description,

db_admin/templates/addEditEntry.html
{% extends "dbadmin_index.html" %}
{% load staticfiles %}

{% block body %}
<table id="SpContent" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td id="SpContent_Container">

            <script type="text/javascript" src="https://safestates.site-ym.com/global_inc/js/ContentScores.js"></script>

            <div id="CustomPageBody">
                <h3>Database Administration - {% if "edit" in request.path %}Edit Entry{% else %}Add New Entry{% endif %}</h3>
                {% include '_messages.html' %}
                <br />
                <h4>Tool Information</h4>
                <hr />
                {{ form.non_field_errors }}
                <form action="." method="POST">{% csrf_token %}
                    <table style="width: 100%">
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong><label for="id_yearDeveloped">Year Developed:</label></strong></td>
                            <td>{{ form.yearDeveloped }} {{ form.yearDeveloped.error_messages }}</td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong><label for="id_name">Tool Name:</label></strong></td>
                            <td>{{ form.name }} {{ form.name.error_messages }}</td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong><label for="id_author">Tool Author:</label></strong></td>
                            <td>{{ form.author }} {{ form.author.error_messages }}</td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong><label for="id_url">URL:</label></strong></td>
                            <td>{{ form.url }} {{ form.url.error_messages }}</td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong><label for="id_description">Tool Description:</label></strong></td>
                            <td>{{ form.description }} {{ form.description.error_messages }}</td>
                        </tr>
                        <tr>
                            <td colspan=2><hr></td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong><label for="id_communitySize">Community Size:</label></strong></td>
                            <td>
                                <table>
                                    <tr>
                                        <td>{{ form.communitySizeUrban }} {{ form.communitySizeUrban.error_messages }}</td>
                                        <td>&nbsp; 1.) Urban</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.communitySizeRural }} {{ form.communitySizeRural.error_messages }}</td>
                                        <td>&nbsp; 2.) Rural</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td colspan=2><hr></td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong>Assessment Focus:</strong></td>
                            <td>
                                <table>
                                    <tr>
                                        <td>{{ form.assessmentFocusDevelopment }} {{ form.assessmentFocusDevelopment.error_messages }}</td>
                                        <td>&nbsp; 1.) Development or Transportation Projects</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.assessmentFocusPhysical }}  {{ form.assessmentFocusPhysical.error_messages }}</td>
                                        <td>&nbsp; 2.) Physical Environment of a Community, Neighborhood, or School</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.assessmentFocusPolicy}} {{ form.assessmentFocusPolicy.error_messages }}</td>
                                        <td>&nbsp; 3.) Policy, Plan, Codes, or Standards</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.assessmentFocusWalkability }} {{ form.assessmentFocusWalkability.error_messages }}</td>
                                        <td>&nbsp; 4.) Walkability, Bikability, and/or Transit Access</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td colspan=2><hr></td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong>Audience:</strong></td>
                            <td>
                                <table>
                                    <tr>
                                        <td>{{ form.audienceElected }} {{ form.audienceElected.error_messages }}</td>
                                        <td>&nbsp; 1.) Elected Officials</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.audienceLaypersons }} {{ form.audienceLaypersons.error_messages }}</td>
                                        <td>&nbsp; 2.) Laypersons</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.audiencePlanners }} {{ form.audiencePlanners.error_messages }}</td>
                                        <td>&nbsp; 3.) Planners</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.audienceProfessionals }} {{ form.audienceProfessionals.error_messages }}</td>
                                        <td>&nbsp; 4.) PH Professionals</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.audienceSchool }} {{ form.audienceSchool.error_messages }}</td>
                                        <td>&nbsp; 5.) School Officials</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td colspan=2><hr></td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td style="width: 20%"><strong>Topics:</strong></td>
                            <td>
                                <table>
                                    <tr>
                                        <td>{{ form.topicTransportation }} {{ form.topicTransportation.error_messages }}</td>
                                        <td>&nbsp; Transportation</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.topicHousing }} {{ form.topicHousing.error_messages }}</td>
                                        <td>&nbsp; Housing</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.topicInvestment }} {{ form.topicInvestment.error_messages }}</td>
                                        <td>&nbsp; Investment</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.topicCompact }} {{ form.topicCompact.error_messages }}</td>
                                        <td>&nbsp; Compact</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.topicHealth }} {{ form.topicHealth.error_messages }}</td>
                                        <td>&nbsp; Health</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.topicPreservation }} {{ form.topicPreservation.error_messages }}</td>
                                        <td>&nbsp; Preservation</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                    <button class="btn btn-primary" type="submit">Save</button> | {% if "edit" in request.path %}<button class="btn" type="button" onclick="window.location = '{% url 'admin_show' entryId %}' ">{% else %}<button type="button" class="btn" onclick="window.location = '{% url 'admin_list' %}' ">{% endif %}Cancel</button>{% if "edit" in request.path %}<div class="pull-right"><a href="{% url 'admin_delete' entryId %}" class="btn btn-danger">Delete This Entry</a></div>{% endif %}
                <br /><br />
                </form>
            </div>
        </td>
    </tr>
</table>
{% endblock %}

db_admin/templates/denied.html
{% extends "dbadmin_index.html" %}
{% load staticfiles %}

{% block body %}
<table id="SpContent" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td id="SpContent_Container">

            <script type="text/javascript" src="https://safestates.site-ym.com/global_inc/js/ContentScores.js"></script>

            <div id="CustomPageBody">
                <h3>You are not authorized</h3>
            </div>
        </td>
    </tr>
</table>
{% endblock %}

db_admin/templates/listEntries.html
{% extends "dbadmin_index.html" %}
{% load staticfiles %}

{% block body %}
<table id="SpContent" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td id="SpContent_Container">

            <script type="text/javascript" src="https://safestates.site-ym.com/global_inc/js/ContentScores.js"></script>

            <div id="CustomPageBody">
                <h3>Database Administration - List Entries</h3>
                {% include '_messages.html' %}
                <a href="{% url 'admin_add' %}" class="btn btn-primary">Add New Entry</a><br />
                <br />
                <table class="table table-striped table-condensed table-hover">
                    <tr>
                        <th><strong>Tool Name</strong></th>
                        <th><strong>Author</strong></th>
                    </tr>
                    {% for tool in tools %}
                    <tr>
                        <td><a href="{% url 'admin_show' tool.id %}">{{ tool.name }}</a></td>
                        <td><a href="{% url 'admin_show' tool.id %}">{{ tool.author }}</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </td>
    </tr>
</table>
{% endblock %}

db_admin/templates/showEntry.html
{% extends "dbadmin_index.html" %}
{% load staticfiles %}

{% block body %}
<table id="SpContent" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td id="SpContent_Container">

            <script type="text/javascript" src="https://safestates.site-ym.com/global_inc/js/ContentScores.js"></script>

            <div id="CustomPageBody">
                <h3>Database Administration - Show Entry</h3>
                {% include '_messages.html' %}
                <br />
                <div class="pull-right"><a href="{% url 'admin_edit' tool.id %}" class="btn btn-primary">Edit This Entry</a></div>

                <h4>Tool Information</h4>
                <hr />
                <table style="width: 100%">
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Year Developed:</strong></td>
                        <td>{{ tool.year_developed }}</td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Tool Name:</strong></td>
                        <td>{{ tool.name }}</td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Tool Author:</strong></td>
                        <td>{{ tool.author }}</td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>URL:</strong></td>
                        <td><a href="{{ tool.url }}" target="_blank">{{ tool.url }}</a></td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Tool Description:</strong></td>
                        <td>{{ tool.description }}</td>
                    </tr>
                    <tr>
                        <td colspan=2><hr></td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Community Size:</strong></td>
                        <td>
                            {% for item in communitySize %}
                            {{ item.selection_verbose }}<br />
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td colspan=2><hr></td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Assessment Focus:</strong></td>
                        <td>
                            {% for item in assessmentFocus %}
                            {{ item.selection_verbose }}<br />
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td colspan=2><hr></td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Audience:</strong></td>
                        <td>
                            {% for item in audience %}
                            {{ item.selection_verbose }}<br />
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td colspan=2><hr></td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td style="width: 20%"><strong>Topics:</strong></td>
                        <td>
                            Transportation: {{ topics.transportation_verbose }}<br />
                            Housing: {{ topics.housing_verbose }}<br />
                            Investment: {{ topics.investment_verbose }}<br />
                            Compact: {{ topics.compact_verbose }}<br />
                            Health: {{ topics.health_verbose }}<br />
                            Preservation: {{ topics.preservation_verbose }}
                        </td>
                    </tr>
                </table>

                <a href="{% url 'admin_list' %}" class="btn btn-primary">Return to list</a>
            </div>
        </td>
    </tr>
</table>
{% endblock %}